version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: padel
      POSTGRES_PASSWORD: padelpass
      POSTGRES_DB: padel_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://padel:padelpass@db:5432/padel_db
      SECRET_KEY: change_me_in_prod
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  pgdata:
